### ISSUE TITLE
Error display isn't enough

### ISSUE THREAD

**Issue by Godley** [dotmesh-io/jupyterlab-plugin#18]
Currently we're just showing "error" apparently. Need to make it display at least a little more detail than that

**Comment by lukemarsden** [comment]
- if I now check the Dotscience tab in Jupyter lab, it says "error", but no additional details are provided.
KAROLIS: JupyterLab plugin needs to show details of an error

Case 1: gap between committing and pushing where agent is polling dotmesh for the intercluster transfer but it's not there yet (shouldn't show up as an error because it's normal)
should be fixed by this
Case 2: network blip on frontend causes jupyter to get disconnected but plugin JS doesn't retry after the blip (no more API calls to status)

KAROLIS: Need to show details of errors in general.
json tags don't match struct values, might be issue

Need to test result of this pipeline: https://gitlab.dotmesh.com/dotmesh/jupyterlab-tensorflow-sync/pipelines/19669
